`ifndef CL_AXIL_REG_ACCESS_DEFINES
`define CL_AXIL_REG_ACCESS_DEFINES
`define CL_NAME cl_axil_reg_access
`define NO_CL_AXIL_DEBUG_ILA
`define ADDR_ACTIVATION   32'h00
`define ADDR_CONTROL      32'h04
`define ADDR_ACCUMULATOR0 32'h08
`define ADDR_ACCUMULATOR1 32'h0C
`define ADDR_ACCUMULATOR2 32'h10
`define ADDR_STATUS       32'h14
`define ADDR_WRITE_COUNT  32'h18
`define INVALID_ADDR_RESP 32'hDEADBEEF
`define AXI_PROT_DEFAULT 3'h0
`define AXI_RESP_OKAY 2'b00
`endif
